name: Build & Test (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./backend/azure-function/azure-function.csproj

      # Build
      - name: Build
        run: dotnet build ./backend/azure-function/azure-function.csproj --no-restore --configuration Release

      # Run tests (if you add test project later)
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
